import type { Logger } from "pino";

import { generateCtdFromFieldsDescriptor } from "../flotiq-ctd-builder.js";
import {
  createCtd,
  ctdNeedsUpdate,
  fetchExistingCtd,
  updateCtd,
} from "./migration-helpers.js";

export const V002_CTDS = [
  generateCtdFromFieldsDescriptor("model_profile", "Config/Model Profile", {
    name: {
      type: "string",
      label: "Name",
      required: true,
      partOfTitle: true,
      readonly: true,
      helpText: "Stable profile name used by tenants.",
    },
    providerBaseUrl: {
      type: "string",
      label: "Provider Base URL",
      required: false,
      helpText:
        "Absolute provider API URL. Leave empty for native Copilot access.",
    },
    providerType: {
      type: "string",
      label: "Provider Type",
      required: false,
      allowedValues: ["openai", "azure", "anthropic"],
      default: "openai",
      helpText: "API compatibility mode: openai, azure, or anthropic.",
    },
    authToken: {
      type: "string",
      label: "Auth Token",
      required: false,
      isPassword: true,
      helpText:
        "Provider credential or GitHub auth token that can access copilot.",
    },
    reviewModel: {
      type: "string",
      label: "Review Model",
      required: false,
      helpText: "Model used for reviews",
    },
    textGenerationModel: {
      type: "string",
      label: "Text Generation Model",
      required: false,
      helpText:
        "Optional model for responding to comments or generating memory entries.",
    },
    wireApi: {
      type: "string",
      label: "Wire API",
      required: false,
      allowedValues: ["completions", "responses"],
      default: "responses",
      helpText: "OpenAI-compatible request format: completions or responses.",
    },
    isDefault: {
      type: "boolean",
      label: "Is Default",
      required: true,
      helpText: "Used when a tenant has no explicit model profile.",
    },
  }),
  generateCtdFromFieldsDescriptor(
    "platform_connection",
    "Config/Platform Connection",
    {
      name: {
        type: "string",
        label: "Name",
        required: true,
        unique: true,
        partOfTitle: true,
        readonly: true,
        helpText: "Immutable, globally unique connection name used in CLI.",
      },
      platform: {
        type: "string",
        label: "Platform",
        required: true,
        partOfTitle: true,
        readonly: true,
        helpText:
          "Provider slug, for example gitlab. Must match a loaded platform module.",
      },
      status: {
        type: "string",
        label: "Status",
        required: true,
        allowedValues: ["setup_required", "ready"],
        helpText:
          "Connection state. Set ready only when the provider configuration is complete.",
      },
      platformConnectionConfigJson: {
        type: "string",
        label: "Platform Connection Config JSON",
        required: true,
        inputType: "textarea",
        helpText:
          "Provider configuration JSON, including credentials. Invalid data can break the connection.",
      },
    },
  ),
  generateCtdFromFieldsDescriptor("tenant", "Config/Tenant", {
    key: {
      type: "string",
      label: "Key",
      required: true,
      partOfTitle: true,
      readonly: true,
      helpText: "Stable key generated by the platform adapter.",
    },
    platform: {
      type: "string",
      label: "Platform",
      required: true,
      partOfTitle: true,
      readonly: true,
      helpText:
        "Provider slug. It must match the selected platform connection.",
    },
    platformConnectionId: {
      type: "datasource",
      label: "Platform Connection",
      required: true,
      relationContentType: "platform_connection",
      readonly: true,
      helpText:
        "Connection used by this tenant. Must match the tenant's platform.",
    },
    platformConfigJson: {
      type: "string",
      label: "Platform Config JSON",
      required: true,
      inputType: "textarea",
      helpText:
        "Provider-owned tenant JSON, including webhook secrets. Edit with caution.",
    },
    modelProfileName: {
      type: "datasource",
      label: "Model Profile",
      required: false,
      relationContentType: "model_profile",
      helpText: "Optional model profile. Empty uses the default profile.",
    },
  }),
  generateCtdFromFieldsDescriptor(
    "interaction_job",
    "Run History/Interaction Job",
    {
      tenantId: {
        type: "datasource",
        label: "Tenant ID",
        required: true,
        relationContentType: "tenant",
        readonly: true,
        helpText: "Tenant that received the interaction.",
      },
      dedupeKey: {
        type: "string",
        label: "Dedupe Key",
        required: true,
        readonly: true,
        helpText: "Internal idempotency key used to prevent duplicate jobs.",
      },
      codeReviewId: {
        type: "number",
        label: "Code Review ID",
        required: true,
        readonly: true,
        helpText:
          "Platform-local merge request or pull request number. Changing it alters job association.",
      },
      commentId: {
        type: "number",
        label: "Comment ID",
        required: true,
        readonly: true,
        helpText:
          "Platform-local triggering comment number. Changing it alters trigger context.",
      },
      headSha: {
        type: "string",
        label: "Head SHA",
        required: true,
        readonly: true,
        helpText:
          "Full commit SHA reviewed by this job. Changing it may make history inconsistent.",
      },
      status: {
        type: "string",
        label: "Status",
        required: true,
        allowedValues: [
          "queued",
          "in_progress",
          "completed",
          "failed",
          "cancelled",
        ],
        helpText: "System-managed job lifecycle state.",
      },
      payloadJson: {
        type: "string",
        label: "Payload JSON",
        required: true,
        inputType: "textarea",
        helpText:
          "Normalized event payload JSON. Invalid structure can prevent job processing.",
      },
      retryCount: {
        type: "number",
        label: "Retry Count",
        required: true,
        readonly: true,
        helpText:
          "Retry attempts already made. Changing this affects retry behavior.",
      },
      lastError: {
        type: "string",
        label: "Last Error",
        required: false,
        readonly: true,
      },
      enqueuedAt: {
        type: "string",
        label: "Enqueued At",
        required: true,
        readonly: true,
        helpText: "ISO 8601 timestamp recorded when the job entered the queue.",
      },
      startedAt: {
        type: "string",
        label: "Started At",
        required: false,
        readonly: true,
        helpText:
          "ISO 8601 timestamp recorded when the job started processing.",
      },
      finishedAt: {
        type: "string",
        label: "Finished At",
        required: false,
        readonly: true,
        helpText:
          "ISO 8601 timestamp recorded when the job finished processing.",
      },
    },
  ),
  generateCtdFromFieldsDescriptor(
    "interaction_run",
    "Run History/Interaction Run",
    {
      interactionJobId: {
        type: "datasource",
        label: "Interaction Job ID",
        required: true,
        relationContentType: "interaction_job",
        readonly: true,
      },
      tenantId: {
        type: "datasource",
        label: "Tenant ID",
        required: true,
        relationContentType: "tenant",
        readonly: true,
      },
      provider: {
        type: "string",
        label: "Provider",
        required: true,
        partOfTitle: true,
        readonly: true,
        helpText:
          "Resolved model provider recorded for this run. Editing changes historical metadata.",
      },
      model: {
        type: "string",
        label: "Model",
        required: false,
        partOfTitle: true,
        readonly: true,
        helpText:
          "Resolved review model recorded for this run. Editing changes historical metadata.",
      },
      modelProfileName: {
        type: "datasource",
        label: "Model Profile",
        required: false,
        relationContentType: "model_profile",
        readonly: true,
      },
      providerBaseUrl: {
        type: "string",
        label: "Provider Base URL",
        required: false,
        readonly: true,
        helpText: "Provider URL recorded for this run.",
      },
      providerType: {
        type: "string",
        label: "Provider Type",
        required: false,
        readonly: true,
        helpText: "Provider API type recorded for this run.",
      },
      textGenerationModel: {
        type: "string",
        label: "Text Generation Model",
        required: false,
        readonly: true,
        helpText: "Resolved text generation model for this run.",
      },
      status: {
        type: "string",
        label: "Status",
        required: true,
        allowedValues: ["in_progress", "completed", "failed", "cancelled"],
        helpText:
          "Run lifecycle state. Manual changes may affect history queries and recovery.",
      },
      resultJson: {
        type: "string",
        label: "Result JSON",
        required: false,
        inputType: "textarea",
        helpText:
          "Structured run result JSON. Invalid data can break history and review output.",
      },
      error: {
        type: "string",
        label: "Error",
        required: false,
        readonly: true,
      },
      startedAt: {
        type: "string",
        label: "Started At",
        required: true,
        readonly: true,
        helpText: "ISO 8601 timestamp recorded when model execution started.",
      },
      finishedAt: {
        type: "string",
        label: "Finished At",
        required: false,
        readonly: true,
      },
    },
  ),
  generateCtdFromFieldsDescriptor(
    "review_finding",
    "Code Review/Review Finding",
    {
      interactionRunId: {
        type: "datasource",
        label: "Interaction Run ID",
        required: true,
        relationContentType: "interaction_run",
        readonly: true,
      },
      identityKey: {
        type: "string",
        label: "Identity Key",
        required: true,
        readonly: true,
        helpText: "Internal stable key used to match this finding across runs.",
      },
      severity: {
        type: "string",
        label: "Severity",
        required: true,
        allowedValues: ["low", "medium", "high", "critical"],
        helpText: "Finding impact: low, medium, high, or critical.",
      },
      category: {
        type: "string",
        label: "Category",
        required: true,
        partOfTitle: true,
        helpText:
          "Finding category used in review summaries and reconciliation.",
      },
      title: {
        type: "string",
        label: "Title",
        required: true,
        partOfTitle: true,
        helpText:
          "Finding title shown in review output. Editing does not update an existing platform comment.",
      },
      body: {
        type: "string",
        label: "Body",
        required: true,
        inputType: "textMarkdown",
        helpText:
          "Finding details shown in review output. Editing does not update an existing platform comment.",
      },
      anchorJson: {
        type: "string",
        label: "Anchor JSON",
        required: false,
        inputType: "textarea",
        helpText:
          "Source anchor JSON. Invalid values can prevent correct inline comment placement.",
      },
      suggestionJson: {
        type: "string",
        label: "Suggestion JSON",
        required: false,
        inputType: "textarea",
        helpText:
          "Optional suggestion JSON. Invalid values can prevent suggestion rendering.",
      },
      status: {
        type: "string",
        label: "Status",
        required: true,
        allowedValues: ["open", "resolved", "dismissed"],
        helpText:
          "Finding state used by reconciliation. Manual changes affect future review summaries.",
      },
    },
  ),
  generateCtdFromFieldsDescriptor(
    "discussion_mapping",
    "Code Review/Discussion Mapping",
    {
      tenantId: {
        type: "datasource",
        label: "Tenant ID",
        required: true,
        relationContentType: "tenant",
        readonly: true,
      },
      codeReviewId: {
        type: "number",
        label: "Code Review ID",
        required: true,
        readonly: true,
        helpText:
          "Platform-local merge request or pull request number. Changing it alters mapping scope.",
      },
      identityKey: {
        type: "string",
        label: "Identity Key",
        required: true,
        readonly: true,
        helpText: "Internal stable key used to match a finding across runs.",
      },
      findingFingerprint: {
        type: "string",
        label: "Finding Fingerprint",
        required: true,
        readonly: true,
        helpText:
          "Internal content fingerprint used during finding reconciliation.",
      },
      category: {
        type: "string",
        label: "Category",
        required: true,
        partOfTitle: true,
        helpText:
          "Finding category recorded for this mapping. Editing affects reconciliation metadata.",
      },
      title: {
        type: "string",
        label: "Title",
        required: true,
        partOfTitle: true,
        helpText:
          "Finding title recorded for this mapping. Editing does not update the platform comment.",
      },
      severity: {
        type: "string",
        label: "Severity",
        required: true,
        allowedValues: ["low", "medium", "high", "critical"],
        helpText:
          "Finding impact recorded for this mapping. Editing affects reconciliation metadata.",
      },
      body: {
        type: "string",
        label: "Body",
        required: true,
        inputType: "textMarkdown",
        helpText:
          "Finding body recorded for this mapping. Editing does not update the platform comment.",
      },
      platformDiscussionId: {
        type: "string",
        label: "Platform Discussion ID",
        required: true,
        readonly: true,
        helpText:
          "Provider-native discussion identifier. Incorrect values can break reconciliation.",
      },
      platformCommentId: {
        type: "number",
        label: "Platform Comment ID",
        required: true,
        readonly: true,
        helpText:
          "Provider-native comment identifier. Incorrect values can break reconciliation.",
      },
      anchorJson: {
        type: "string",
        label: "Anchor JSON",
        required: false,
        inputType: "textarea",
        helpText:
          "Source anchor JSON. Invalid values can break inline discussion reconciliation.",
      },
      positionJson: {
        type: "string",
        label: "Position JSON",
        required: false,
        inputType: "textarea",
        helpText:
          "Provider-native position JSON. Invalid values can break inline discussion updates.",
      },
      botDiscussion: {
        type: "boolean",
        label: "Bot Discussion",
        required: true,
        helpText:
          "Whether the discussion was created by the configured bot account.",
      },
      botComment: {
        type: "boolean",
        label: "Bot Comment",
        required: true,
        helpText: "Whether the mapped comment was created by the bot account.",
      },
      commentAuthorId: {
        type: "number",
        label: "Comment Author ID",
        required: false,
        helpText:
          "Provider-native author ID. Editing can affect bot comment detection.",
      },
      commentAuthorUsername: {
        type: "string",
        label: "Comment Author Username",
        required: false,
        helpText:
          "Provider-native author username. Editing can affect bot comment detection.",
      },
      status: {
        type: "string",
        label: "Status",
        required: true,
        allowedValues: ["open", "resolved"],
        helpText:
          "Mapped discussion state. Manual changes affect finding reconciliation.",
      },
      lastInteractionRunId: {
        type: "datasource",
        label: "Last Interaction Run ID",
        required: false,
        relationContentType: "interaction_run",
        readonly: true,
      },
    },
  ),
  generateCtdFromFieldsDescriptor(
    "code_review_snapshot",
    "Code Review/Snapshot",
    {
      interactionJobId: {
        type: "datasource",
        label: "Interaction Job ID",
        required: true,
        relationContentType: "interaction_job",
        readonly: true,
      },
      tenantId: {
        type: "datasource",
        label: "Tenant ID",
        required: true,
        relationContentType: "tenant",
        readonly: true,
      },
      codeReviewId: {
        type: "number",
        label: "Code Review ID",
        required: true,
        partOfTitle: true,
        readonly: true,
        helpText:
          "Platform-local merge request or pull request number represented by this snapshot.",
      },
      headSha: {
        type: "string",
        label: "Head SHA",
        required: true,
        partOfTitle: true,
        readonly: true,
        helpText:
          "Full commit SHA represented by this snapshot. Keep it consistent with snapshot JSON.",
      },
      codeReviewJson: {
        type: "string",
        label: "Code Review JSON",
        required: true,
        inputType: "textarea",
        helpText:
          "Normalized code review JSON. Changes alter the historical review context.",
      },
      versionsJson: {
        type: "string",
        label: "Versions JSON",
        required: true,
        inputType: "textarea",
        helpText:
          "Provider review versions JSON. Keep values consistent with the code review metadata.",
      },
      changesJson: {
        type: "string",
        label: "Changes JSON",
        required: true,
        inputType: "textarea",
        helpText:
          "Changed files and patches JSON used as review context. Invalid data can break replay.",
      },
      commentsJson: {
        type: "string",
        label: "Comments JSON",
        required: true,
        inputType: "textarea",
        helpText:
          "Review comments JSON used as historical context. Invalid data can break replay.",
      },
      discussionsJson: {
        type: "string",
        label: "Discussions JSON",
        required: true,
        inputType: "textarea",
        helpText:
          "Review discussions JSON used as historical context. Invalid data can break replay.",
      },
      instructionsJson: {
        type: "string",
        label: "Instructions JSON",
        required: true,
        inputType: "textarea",
        helpText:
          "Resolved review instructions JSON. Changes alter the historical prompt context.",
      },
      projectMemoryJson: {
        type: "string",
        label: "Project Memory JSON",
        required: false,
        inputType: "textarea",
        helpText:
          "Project memory JSON supplied to the review. Changes alter the historical prompt context.",
      },
      workspaceStrategy: {
        type: "string",
        label: "Workspace Strategy",
        required: true,
        helpText:
          "Workspace strategy recorded for this snapshot. Editing changes historical metadata.",
      },
    },
  ),
  generateCtdFromFieldsDescriptor(
    "interaction_run_metrics",
    "Run History/Interaction Run Metrics",
    {
      interactionRunId: {
        type: "datasource",
        label: "Interaction Run ID",
        required: true,
        relationContentType: "interaction_run",
        readonly: true,
        helpText: "Interaction run measured by this record.",
      },
      triggerKind: {
        type: "string",
        label: "Trigger Kind",
        required: false,
        partOfTitle: true,
        helpText:
          "Kind of event that initiated the measured run. Editing changes reporting metadata.",
      },
      promptMode: {
        type: "string",
        label: "Prompt Mode",
        required: false,
        partOfTitle: true,
        helpText:
          "Prompt construction mode used for the run. Editing changes reporting metadata.",
      },
      promptChars: {
        type: "number",
        label: "Prompt Chars",
        required: true,
        helpText: "Prompt size in characters.",
      },
      promptContextChangedFiles: {
        type: "number",
        label: "Prompt Context Changed Files",
        required: true,
        helpText: "Number of changed files included in prompt context.",
      },
      promptContextPriorDiscussions: {
        type: "number",
        label: "Prompt Context Prior Discussions",
        required: true,
        helpText: "Number of prior discussions included in prompt context.",
      },
      promptContextComments: {
        type: "number",
        label: "Prompt Context Comments",
        required: true,
        helpText: "Number of comments included in prompt context.",
      },
      assistantTurns: {
        type: "number",
        label: "Assistant Turns",
        required: true,
        helpText: "Number of assistant turns recorded for the run.",
      },
      assistantCalls: {
        type: "number",
        label: "Assistant Calls",
        required: true,
        helpText: "Number of assistant API calls recorded for the run.",
      },
      toolExecutions: {
        type: "number",
        label: "Tool Executions",
        required: true,
        helpText: "Total tool executions recorded for the run.",
      },
      viewToolCalls: {
        type: "number",
        label: "View Tool Calls",
        required: true,
        helpText: "Number of file-view tool calls recorded for the run.",
      },
      globToolCalls: {
        type: "number",
        label: "Glob Tool Calls",
        required: true,
        helpText: "Number of file-glob tool calls recorded for the run.",
      },
      inputTokens: {
        type: "number",
        label: "Input Tokens",
        required: true,
        helpText: "Provider-reported input token count.",
      },
      outputTokens: {
        type: "number",
        label: "Output Tokens",
        required: true,
        helpText: "Provider-reported output token count.",
      },
      cacheReadTokens: {
        type: "number",
        label: "Cache Read Tokens",
        required: true,
        helpText: "Provider-reported cache read token count.",
      },
      cacheWriteTokens: {
        type: "number",
        label: "Cache Write Tokens",
        required: true,
        helpText: "Provider-reported cache write token count.",
      },
      reasoningTokens: {
        type: "number",
        label: "Reasoning Tokens",
        required: true,
        helpText: "Provider-reported reasoning token count.",
      },
      apiDurationMs: {
        type: "number",
        label: "API Duration Ms",
        required: true,
        helpText: "Total provider API duration in milliseconds.",
      },
      premiumRequests: {
        type: "number",
        label: "Premium Requests",
        required: true,
        helpText: "Provider-reported premium request count.",
      },
      repeatedViewReads: {
        type: "number",
        label: "Repeated View Reads",
        required: true,
        helpText: "Number of repeated file reads detected during the run.",
      },
      repeatedViewPathsJson: {
        type: "string",
        label: "Repeated View Paths JSON",
        required: true,
        inputType: "textarea",
        helpText:
          "Repeatedly viewed file paths encoded as JSON for diagnostics.",
      },
    },
  ),
  generateCtdFromFieldsDescriptor("migrations", "Config/Migrations History", {
    name: {
      type: "string",
      label: "Name",
      required: true,
      unique: true,
      partOfTitle: true,
      readonly: true,
      helpText: "Applied migration identifier managed by the storage adapter.",
    },
  }),
] as const;

export default async function ensureV002CtdsExist(
  apiKey: string,
  logger?: Logger,
): Promise<void> {
  if (!apiKey) {
    throw new Error(
      "FLOTIQ_API_KEY is not set. Cannot ensure CTDs exist without API key.",
    );
  }

  for (const ctd of V002_CTDS) {
    logger?.info({ ctdName: ctd.name }, "Ensuring Flotiq CTD exists.");
    const existingCtd = await fetchExistingCtd(ctd.name, apiKey, logger);

    if (!existingCtd) {
      await createCtd(ctd, apiKey, logger);
      continue;
    }

    if (!ctdNeedsUpdate(existingCtd, ctd)) {
      logger?.info({ ctdName: ctd.name }, "Flotiq CTD already exists.");
      continue;
    }

    await updateCtd(ctd.name, ctd, apiKey, logger);
  }
}
