/**
 * This file was generated by flotiq-api-typegen command
 * Generated at: 2026-05-07T15:39:26.928Z
 */

import {
  DataLink,
  ApiRequest,
  BaseObject,
  SearchParams,
  HydratedSearchResponse,
  InternalGeneratedFormsBase,
  InternalGeneratedForms,
  InternalGeneratedFormsHydrated,
  InternalGeneratedFormsHydratedTwice,
  InternalMediaBase,
  InternalMedia,
  InternalMediaHydrated,
  InternalMediaHydratedTwice,
  InternalPluginSettingsBase,
  InternalPluginSettings,
  InternalPluginSettingsHydrated,
  InternalPluginSettingsHydratedTwice,
  InternalTagBase,
  InternalTag,
  InternalTagHydrated,
  InternalTagHydratedTwice,
  InternalWebhooksBase,
  InternalWebhooks,
  InternalWebhooksHydrated,
  InternalWebhooksHydratedTwice,
} from "@flotiq/flotiq-api-sdk";

type StringWithAutocomplete<T> = T | (string & Record<never, never>);

declare module "@flotiq/flotiq-api-sdk" {
  export type AnySpaceCTD =
    | DiscussionMapping
    | InteractionJob
    | InteractionRun
    | InteractionRunMetrics
    | CodeReviewSnapshot
    | Migrations
    | ModelProfile
    | PreviousCompletedInteraction
    | PriorReviewFinding
    | ReviewFinding
    | Tenant
    | InternalGeneratedForms
    | InternalMedia
    | InternalPluginSettings
    | InternalTag
    | InternalWebhooks;

  export type AnySpaceCTDHydrated =
    | DiscussionMappingHydrated
    | InteractionJobHydrated
    | InteractionRunHydrated
    | InteractionRunMetricsHydrated
    | CodeReviewSnapshotHydrated
    | MigrationsHydrated
    | ModelProfileHydrated
    | PreviousCompletedInteractionHydrated
    | PriorReviewFindingHydrated
    | ReviewFindingHydrated
    | TenantHydrated
    | InternalGeneratedFormsHydrated
    | InternalMediaHydrated
    | InternalPluginSettingsHydrated
    | InternalTagHydrated
    | InternalWebhooksHydrated;

  export type AnySpaceCTDHydratedTwice =
    | DiscussionMappingHydratedTwice
    | InteractionJobHydratedTwice
    | InteractionRunHydratedTwice
    | InteractionRunMetricsHydratedTwice
    | CodeReviewSnapshotHydratedTwice
    | MigrationsHydratedTwice
    | ModelProfileHydratedTwice
    | PreviousCompletedInteractionHydratedTwice
    | PriorReviewFindingHydratedTwice
    | ReviewFindingHydratedTwice
    | TenantHydratedTwice
    | InternalGeneratedFormsHydratedTwice
    | InternalMediaHydratedTwice
    | InternalPluginSettingsHydratedTwice
    | InternalTagHydratedTwice
    | InternalWebhooksHydratedTwice;

  export type AnySpaceCTDBase =
    | DiscussionMappingBase
    | InteractionJobBase
    | InteractionRunBase
    | InteractionRunMetricsBase
    | CodeReviewSnapshotBase
    | MigrationsBase
    | ModelProfileBase
    | PreviousCompletedInteractionBase
    | PriorReviewFindingBase
    | ReviewFindingBase
    | TenantBase
    | InternalGeneratedFormsBase
    | InternalMediaBase
    | InternalPluginSettingsBase
    | InternalTagBase
    | InternalWebhooksBase;

  // #region discussion_mapping

  export interface DiscussionMappingBase extends BaseObject<"discussion_mapping"> {
    tenantId: string;
    codeReviewId: number;
    identityKey: string;
    findingFingerprint: string;
    title: string;
    severity: string;
    category: string;
    body: string;
    platformThreadId: string;
    platformCommentId: number;
    anchorJson?: string;
    positionJson?: string;
    botDiscussion: boolean;
    botNote: boolean;
    noteAuthorId?: number;
    noteAuthorUsername?: string;
    status: string;
    lastInteractionRunId?: string;
  }

  export interface DiscussionMapping extends DiscussionMappingBase {}

  export interface DiscussionMappingHydrated extends DiscussionMappingBase {}

  export interface DiscussionMappingHydratedTwice extends DiscussionMappingBase {}

  export namespace DiscussionMapping {
    export type FilterableFields = StringWithAutocomplete<
      | "tenantId"
      | "codeReviewId"
      | "identityKey"
      | "findingFingerprint"
      | "title"
      | "severity"
      | "category"
      | "body"
      | "platformThreadId"
      | "platformCommentId"
      | "anchorJson"
      | "positionJson"
      | "botDiscussion"
      | "botNote"
      | "noteAuthorId"
      | "noteAuthorUsername"
      | "status"
      | "lastInteractionRunId"
    >;
  }

  // #endregion

  // #region interaction_job

  export interface InteractionJobBase extends BaseObject<"interaction_job"> {
    tenantId: string;
    dedupeKey: string;
    codeReviewId: number;
    noteId: number;
    headSha: string;
    status: string;
    payloadJson: string;
    retryCount: number;
    lastError?: string;
    enqueuedAt: string;
    startedAt?: string;
    finishedAt?: string;
  }

  export interface InteractionJob extends InteractionJobBase {}

  export interface InteractionJobHydrated extends InteractionJobBase {}

  export interface InteractionJobHydratedTwice extends InteractionJobBase {}

  export namespace InteractionJob {
    export type FilterableFields = StringWithAutocomplete<
      | "tenantId"
      | "dedupeKey"
      | "codeReviewId"
      | "noteId"
      | "headSha"
      | "status"
      | "payloadJson"
      | "retryCount"
      | "lastError"
      | "enqueuedAt"
      | "startedAt"
      | "finishedAt"
    >;
  }

  // #endregion

  // #region interaction_run

  export interface InteractionRunBase extends BaseObject<"interaction_run"> {
    interactionJobId: string;
    tenantId: string;
    provider: string;
    model?: string;
    modelProfileName?: string;
    providerBaseUrl?: string;
    providerType?: string;
    textGenerationModel?: string;
    status: string;
    resultJson?: string;
    error?: string;
    startedAt: string;
    finishedAt?: string;
  }

  export interface InteractionRun extends InteractionRunBase {}

  export interface InteractionRunHydrated extends InteractionRunBase {}

  export interface InteractionRunHydratedTwice extends InteractionRunBase {}

  export namespace InteractionRun {
    export type FilterableFields = StringWithAutocomplete<
      | "interactionJobId"
      | "tenantId"
      | "provider"
      | "model"
      | "modelProfileName"
      | "providerBaseUrl"
      | "providerType"
      | "textGenerationModel"
      | "status"
      | "resultJson"
      | "error"
      | "startedAt"
      | "finishedAt"
    >;
  }

  // #endregion

  // #region interaction_run_metrics

  export interface InteractionRunMetricsBase extends BaseObject<"interaction_run_metrics"> {
    interactionRunId: string;
    triggerKind?: string;
    promptMode?: string;
    promptChars: number;
    promptContextChangedFiles: number;
    promptContextPriorThreads: number;
    promptContextNotes: number;
    assistantTurns: number;
    assistantCalls: number;
    toolExecutions: number;
    viewToolCalls: number;
    globToolCalls: number;
    inputTokens: number;
    outputTokens: number;
    cacheReadTokens: number;
    cacheWriteTokens: number;
    reasoningTokens: number;
    apiDurationMs: number;
    premiumRequests: number;
    repeatedViewReads: number;
    repeatedViewPathsJson: string;
  }

  export interface InteractionRunMetrics extends InteractionRunMetricsBase {}

  export interface InteractionRunMetricsHydrated extends InteractionRunMetricsBase {}

  export interface InteractionRunMetricsHydratedTwice extends InteractionRunMetricsBase {}

  export namespace InteractionRunMetrics {
    export type FilterableFields = StringWithAutocomplete<
      | "interactionRunId"
      | "triggerKind"
      | "promptMode"
      | "promptChars"
      | "promptContextChangedFiles"
      | "promptContextPriorThreads"
      | "promptContextNotes"
      | "assistantTurns"
      | "assistantCalls"
      | "toolExecutions"
      | "viewToolCalls"
      | "globToolCalls"
      | "inputTokens"
      | "outputTokens"
      | "cacheReadTokens"
      | "cacheWriteTokens"
      | "reasoningTokens"
      | "apiDurationMs"
      | "premiumRequests"
      | "repeatedViewReads"
      | "repeatedViewPathsJson"
    >;
  }

  // #endregion

  // #region code_review_snapshot

  export interface CodeReviewSnapshotBase extends BaseObject<"code_review_snapshot"> {
    interactionJobId: string;
    tenantId: string;
    codeReviewId: number;
    headSha: string;
    codeReviewJson: string;
    versionsJson: string;
    changesJson: string;
    notesJson: string;
    discussionsJson: string;
    instructionsJson: string;
    projectMemoryJson?: string;
    workspaceStrategy: string;
  }

  export interface CodeReviewSnapshot extends CodeReviewSnapshotBase {}

  export interface CodeReviewSnapshotHydrated extends CodeReviewSnapshotBase {}

  export interface CodeReviewSnapshotHydratedTwice extends CodeReviewSnapshotBase {}

  export namespace CodeReviewSnapshot {
    export type FilterableFields = StringWithAutocomplete<
      | "interactionJobId"
      | "tenantId"
      | "codeReviewId"
      | "headSha"
      | "codeReviewJson"
      | "versionsJson"
      | "changesJson"
      | "notesJson"
      | "discussionsJson"
      | "instructionsJson"
      | "projectMemoryJson"
      | "workspaceStrategy"
    >;
  }

  // #endregion

  // #region migrations

  export interface MigrationsBase extends BaseObject<"migrations"> {
    name: string;
  }

  export interface Migrations extends MigrationsBase {}

  export interface MigrationsHydrated extends MigrationsBase {}

  export interface MigrationsHydratedTwice extends MigrationsBase {}

  export namespace Migrations {
    export type FilterableFields = StringWithAutocomplete<"name">;
  }

  // #endregion

  // #region model_profile

  export interface ModelProfileBase extends BaseObject<"model_profile"> {
    name: string;
    providerBaseUrl?: string;
    providerType?: string;
    authToken?: string;
    reviewModel?: string;
    textGenerationModel?: string;
    wireApi?: string;
    isDefault: boolean;
  }

  export interface ModelProfile extends ModelProfileBase {}

  export interface ModelProfileHydrated extends ModelProfileBase {}

  export interface ModelProfileHydratedTwice extends ModelProfileBase {}

  export namespace ModelProfile {
    export type FilterableFields = StringWithAutocomplete<
      | "name"
      | "providerBaseUrl"
      | "providerType"
      | "authToken"
      | "reviewModel"
      | "textGenerationModel"
      | "wireApi"
      | "isDefault"
    >;
  }

  // #endregion

  // #region previous_completed_interaction

  export interface PreviousCompletedInteractionBase extends BaseObject<"previous_completed_interaction"> {
    interactionRunId: string;
    interactionJobId: string;
    finishedAt: string;
    headSha: string;
    resultJson: string;
    snapshot: string;
  }

  export interface PreviousCompletedInteraction extends PreviousCompletedInteractionBase {}

  export interface PreviousCompletedInteractionHydrated extends PreviousCompletedInteractionBase {}

  export interface PreviousCompletedInteractionHydratedTwice extends PreviousCompletedInteractionBase {}

  export namespace PreviousCompletedInteraction {
    export type FilterableFields = StringWithAutocomplete<
      | "interactionRunId"
      | "interactionJobId"
      | "finishedAt"
      | "headSha"
      | "resultJson"
      | "snapshot"
    >;
  }

  // #endregion

  // #region prior_review_finding

  export interface PriorReviewFindingBase extends BaseObject<"prior_review_finding"> {
    findingId: string;
    identityKey: string;
    status: string;
    title: string;
    body: string;
    severity: string;
    category: string;
    anchor?: string;
    suggestion?: string;
    interactionRunId: string;
    reviewedAt: string;
    headSha: string;
  }

  export interface PriorReviewFinding extends PriorReviewFindingBase {}

  export interface PriorReviewFindingHydrated extends PriorReviewFindingBase {}

  export interface PriorReviewFindingHydratedTwice extends PriorReviewFindingBase {}

  export namespace PriorReviewFinding {
    export type FilterableFields = StringWithAutocomplete<
      | "findingId"
      | "identityKey"
      | "status"
      | "title"
      | "body"
      | "severity"
      | "category"
      | "anchor"
      | "suggestion"
      | "interactionRunId"
      | "reviewedAt"
      | "headSha"
    >;
  }

  // #endregion

  // #region review_finding

  export interface ReviewFindingBase extends BaseObject<"review_finding"> {
    interactionRunId: string;
    identityKey: string;
    severity: string;
    category: string;
    title: string;
    body: string;
    anchorJson?: string;
    suggestionJson?: string;
    status: string;
  }

  export interface ReviewFinding extends ReviewFindingBase {}

  export interface ReviewFindingHydrated extends ReviewFindingBase {}

  export interface ReviewFindingHydratedTwice extends ReviewFindingBase {}

  export namespace ReviewFinding {
    export type FilterableFields = StringWithAutocomplete<
      | "interactionRunId"
      | "identityKey"
      | "severity"
      | "category"
      | "title"
      | "body"
      | "anchorJson"
      | "suggestionJson"
      | "status"
    >;
  }

  // #endregion

  // #region tenant

  export interface TenantBase extends BaseObject<"tenant"> {
    key: string;
    platform: string;
    platformConfigJson: string;
    modelProfileName?: string;
  }

  export interface Tenant extends TenantBase {}

  export interface TenantHydrated extends TenantBase {}

  export interface TenantHydratedTwice extends TenantBase {}

  export namespace Tenant {
    export type FilterableFields = StringWithAutocomplete<
      "key" | "platform" | "platformConfigJson" | "modelProfileName"
    >;
  }

  // #endregion

  export interface FlotiqObjectAPI {
    discussion_mapping: ApiRequest<
      DiscussionMapping,
      DiscussionMappingHydrated,
      DiscussionMappingHydratedTwice,
      DiscussionMapping.FilterableFields
    >;

    interaction_job: ApiRequest<
      InteractionJob,
      InteractionJobHydrated,
      InteractionJobHydratedTwice,
      InteractionJob.FilterableFields
    >;

    interaction_run: ApiRequest<
      InteractionRun,
      InteractionRunHydrated,
      InteractionRunHydratedTwice,
      InteractionRun.FilterableFields
    >;

    interaction_run_metrics: ApiRequest<
      InteractionRunMetrics,
      InteractionRunMetricsHydrated,
      InteractionRunMetricsHydratedTwice,
      InteractionRunMetrics.FilterableFields
    >;

    code_review_snapshot: ApiRequest<
      CodeReviewSnapshot,
      CodeReviewSnapshotHydrated,
      CodeReviewSnapshotHydratedTwice,
      CodeReviewSnapshot.FilterableFields
    >;

    migrations: ApiRequest<
      Migrations,
      MigrationsHydrated,
      MigrationsHydratedTwice,
      Migrations.FilterableFields
    >;

    model_profile: ApiRequest<
      ModelProfile,
      ModelProfileHydrated,
      ModelProfileHydratedTwice,
      ModelProfile.FilterableFields
    >;

    previous_completed_interaction: ApiRequest<
      PreviousCompletedInteraction,
      PreviousCompletedInteractionHydrated,
      PreviousCompletedInteractionHydratedTwice,
      PreviousCompletedInteraction.FilterableFields
    >;

    prior_review_finding: ApiRequest<
      PriorReviewFinding,
      PriorReviewFindingHydrated,
      PriorReviewFindingHydratedTwice,
      PriorReviewFinding.FilterableFields
    >;

    review_finding: ApiRequest<
      ReviewFinding,
      ReviewFindingHydrated,
      ReviewFindingHydratedTwice,
      ReviewFinding.FilterableFields
    >;

    tenant: ApiRequest<
      Tenant,
      TenantHydrated,
      TenantHydratedTwice,
      Tenant.FilterableFields
    >;

    _generated_forms: ApiRequest<
      InternalGeneratedForms,
      InternalGeneratedFormsHydrated,
      InternalGeneratedFormsHydratedTwice,
      InternalGeneratedForms.FilterableFields
    >;

    _media: ApiRequest<
      InternalMedia,
      InternalMediaHydrated,
      InternalMediaHydratedTwice,
      InternalMedia.FilterableFields
    >;

    _plugin_settings: ApiRequest<
      InternalPluginSettings,
      InternalPluginSettingsHydrated,
      InternalPluginSettingsHydratedTwice,
      InternalPluginSettings.FilterableFields
    >;

    _tag: ApiRequest<
      InternalTag,
      InternalTagHydrated,
      InternalTagHydratedTwice,
      InternalTag.FilterableFields
    >;

    _webhooks: ApiRequest<
      InternalWebhooks,
      InternalWebhooksHydrated,
      InternalWebhooksHydratedTwice,
      InternalWebhooks.FilterableFields
    >;
  }

  export interface FlotiqSearchAPI {
    query<P extends SearchParams>(
      params?: P,
    ): Promise<
      HydratedSearchResponse<
        P,
        AnySpaceCTD,
        AnySpaceCTDHydrated,
        AnySpaceCTDHydratedTwice
      >
    >;
  }
}
