/**
 * This file was generated by flotiq-api-typegen command
 * Generated at: 2026-07-16T23:36:17.844Z
 */

import {
  DataLink,
  ApiRequest,
  BaseObject,
  SearchParams,
  HydratedSearchResponse,
  InternalGeneratedFormsBase,
  InternalGeneratedForms,
  InternalGeneratedFormsHydrated,
  InternalGeneratedFormsHydratedTwice,
  InternalMediaBase,
  InternalMedia,
  InternalMediaHydrated,
  InternalMediaHydratedTwice,
  InternalPluginSettingsBase,
  InternalPluginSettings,
  InternalPluginSettingsHydrated,
  InternalPluginSettingsHydratedTwice,
  InternalTagBase,
  InternalTag,
  InternalTagHydrated,
  InternalTagHydratedTwice,
  InternalWebhooksBase,
  InternalWebhooks,
  InternalWebhooksHydrated,
  InternalWebhooksHydratedTwice,
} from "@flotiq/flotiq-api-sdk";

type StringWithAutocomplete<T> = T | (string & Record<never, never>);

declare module "@flotiq/flotiq-api-sdk" {
  export type AnySpaceCTD =
    | CodeReviewSnapshot
    | DiscussionMapping
    | InteractionJob
    | InteractionRun
    | InteractionRunMetrics
    | Migrations
    | ModelProfile
    | PlatformConnection
    | ProjectMemory
    | ReviewFinding
    | Tenant
    | InternalGeneratedForms
    | InternalMedia
    | InternalPluginSettings
    | InternalTag
    | InternalWebhooks;

  export type AnySpaceCTDHydrated =
    | CodeReviewSnapshotHydrated
    | DiscussionMappingHydrated
    | InteractionJobHydrated
    | InteractionRunHydrated
    | InteractionRunMetricsHydrated
    | MigrationsHydrated
    | ModelProfileHydrated
    | PlatformConnectionHydrated
    | ProjectMemoryHydrated
    | ReviewFindingHydrated
    | TenantHydrated
    | InternalGeneratedFormsHydrated
    | InternalMediaHydrated
    | InternalPluginSettingsHydrated
    | InternalTagHydrated
    | InternalWebhooksHydrated;

  export type AnySpaceCTDHydratedTwice =
    | CodeReviewSnapshotHydratedTwice
    | DiscussionMappingHydratedTwice
    | InteractionJobHydratedTwice
    | InteractionRunHydratedTwice
    | InteractionRunMetricsHydratedTwice
    | MigrationsHydratedTwice
    | ModelProfileHydratedTwice
    | PlatformConnectionHydratedTwice
    | ProjectMemoryHydratedTwice
    | ReviewFindingHydratedTwice
    | TenantHydratedTwice
    | InternalGeneratedFormsHydratedTwice
    | InternalMediaHydratedTwice
    | InternalPluginSettingsHydratedTwice
    | InternalTagHydratedTwice
    | InternalWebhooksHydratedTwice;

  export type AnySpaceCTDBase =
    | CodeReviewSnapshotBase
    | DiscussionMappingBase
    | InteractionJobBase
    | InteractionRunBase
    | InteractionRunMetricsBase
    | MigrationsBase
    | ModelProfileBase
    | PlatformConnectionBase
    | ProjectMemoryBase
    | ReviewFindingBase
    | TenantBase
    | InternalGeneratedFormsBase
    | InternalMediaBase
    | InternalPluginSettingsBase
    | InternalTagBase
    | InternalWebhooksBase;

  // #region code_review_snapshot

  export interface CodeReviewSnapshotBase extends BaseObject<"code_review_snapshot"> {
    interactionJobId:
      | Array<DataLink>
      | Array<InteractionJob>
      | Array<InteractionJobHydrated>
      | Array<InteractionJobHydratedTwice>
      | Array<InteractionJobBase>;
    tenantId:
      | Array<DataLink>
      | Array<Tenant>
      | Array<TenantHydrated>
      | Array<TenantHydratedTwice>
      | Array<TenantBase>;

    /**
     * Platform-local merge request or pull request number represented by this snapshot.
     */
    codeReviewId: number;

    /**
     * Full commit SHA represented by this snapshot. Keep it consistent with snapshot JSON.
     */
    headSha: string;

    /**
     * Normalized code review JSON. Changes alter the historical review context.
     */
    codeReviewJson: string;

    /**
     * Provider review versions JSON. Keep values consistent with the code review metadata.
     */
    versionsJson: string;

    /**
     * Changed files and patches JSON used as review context. Invalid data can break replay.
     */
    changesJson: string;

    /**
     * Review comments JSON used as historical context. Invalid data can break replay.
     */
    commentsJson: string;

    /**
     * Review discussions JSON used as historical context. Invalid data can break replay.
     */
    discussionsJson: string;

    /**
     * Resolved review instructions JSON. Changes alter the historical prompt context.
     */
    instructionsJson: string;

    /**
     * Project memory JSON supplied to the review. Changes alter the historical prompt context.
     */
    projectMemoryJson?: string;

    /**
     * Workspace strategy recorded for this snapshot. Editing changes historical metadata.
     */
    workspaceStrategy: string;

    /**
     * Logical interaction-run id this snapshot belongs to. Empty for snapshots migrated before v005.
     */
    interactionRunId?: string;
  }

  export interface CodeReviewSnapshot extends CodeReviewSnapshotBase {
    interactionJobId: Array<DataLink>;
    tenantId: Array<DataLink>;
  }

  export interface CodeReviewSnapshotHydrated extends CodeReviewSnapshotBase {
    interactionJobId: Array<InteractionJob>;
    tenantId: Array<Tenant>;
  }

  export interface CodeReviewSnapshotHydratedTwice extends CodeReviewSnapshotBase {
    interactionJobId: Array<InteractionJobHydrated>;
    tenantId: Array<TenantHydrated>;
  }

  export namespace CodeReviewSnapshot {
    export type FilterableFields = StringWithAutocomplete<
      | "interactionJobId"
      | "interactionJobId[*].type"
      | "interactionJobId[*].dataUrl"
      | "tenantId"
      | "tenantId[*].type"
      | "tenantId[*].dataUrl"
      | "codeReviewId"
      | "headSha"
      | "codeReviewJson"
      | "versionsJson"
      | "changesJson"
      | "commentsJson"
      | "discussionsJson"
      | "instructionsJson"
      | "projectMemoryJson"
      | "workspaceStrategy"
      | "interactionRunId"
    >;
  }

  // #endregion

  // #region discussion_mapping

  export interface DiscussionMappingBase extends BaseObject<"discussion_mapping"> {
    tenantId:
      | Array<DataLink>
      | Array<Tenant>
      | Array<TenantHydrated>
      | Array<TenantHydratedTwice>
      | Array<TenantBase>;

    /**
     * Platform-local merge request or pull request number. Changing it alters mapping scope.
     */
    codeReviewId: number;

    /**
     * Internal stable key used to match a finding across runs.
     */
    identityKey: string;

    /**
     * Internal content fingerprint used during finding reconciliation.
     */
    findingFingerprint: string;

    /**
     * Finding category recorded for this mapping. Editing affects reconciliation metadata.
     */
    category: string;

    /**
     * Finding title recorded for this mapping. Editing does not update the platform comment.
     */
    title: string;

    /**
     * Finding impact recorded for this mapping. Editing affects reconciliation metadata.
     */
    severity: "low" | "medium" | "high" | "critical";

    /**
     * Finding body recorded for this mapping. Editing does not update the platform comment.
     */
    body: string;

    /**
     * Provider-native discussion identifier. Incorrect values can break reconciliation.
     */
    platformDiscussionId: string;

    /**
     * Provider-native comment identifier. Incorrect values can break reconciliation.
     */
    platformCommentId: number;

    /**
     * Source anchor JSON. Invalid values can break inline discussion reconciliation.
     */
    anchorJson?: string;

    /**
     * Provider-native position JSON. Invalid values can break inline discussion updates.
     */
    positionJson?: string;

    /**
     * Whether the discussion was created by the configured bot account.
     */
    botDiscussion: boolean;

    /**
     * Whether the mapped comment was created by the bot account.
     */
    botComment: boolean;

    /**
     * Provider-native author ID. Editing can affect bot comment detection.
     */
    commentAuthorId?: number;

    /**
     * Provider-native author username. Editing can affect bot comment detection.
     */
    commentAuthorUsername?: string;

    /**
     * Mapped discussion state. Manual changes affect finding reconciliation.
     */
    status: "open" | "resolved";
    lastInteractionRunId?:
      | Array<DataLink>
      | Array<InteractionRun>
      | Array<InteractionRunHydrated>
      | Array<InteractionRunHydratedTwice>
      | Array<InteractionRunBase>;
  }

  export interface DiscussionMapping extends DiscussionMappingBase {
    tenantId: Array<DataLink>;
    lastInteractionRunId?: Array<DataLink>;
  }

  export interface DiscussionMappingHydrated extends DiscussionMappingBase {
    tenantId: Array<Tenant>;
    lastInteractionRunId?: Array<InteractionRun>;
  }

  export interface DiscussionMappingHydratedTwice extends DiscussionMappingBase {
    tenantId: Array<TenantHydrated>;
    lastInteractionRunId?: Array<InteractionRunHydrated>;
  }

  export namespace DiscussionMapping {
    export type FilterableFields = StringWithAutocomplete<
      | "tenantId"
      | "tenantId[*].type"
      | "tenantId[*].dataUrl"
      | "codeReviewId"
      | "identityKey"
      | "findingFingerprint"
      | "category"
      | "title"
      | "severity"
      | "body"
      | "platformDiscussionId"
      | "platformCommentId"
      | "anchorJson"
      | "positionJson"
      | "botDiscussion"
      | "botComment"
      | "commentAuthorId"
      | "commentAuthorUsername"
      | "status"
      | "lastInteractionRunId"
      | "lastInteractionRunId[*].type"
      | "lastInteractionRunId[*].dataUrl"
    >;
  }

  // #endregion

  // #region interaction_job

  export interface InteractionJobBase extends BaseObject<"interaction_job"> {
    /**
     * Tenant that received the interaction.
     */
    tenantId:
      | Array<DataLink>
      | Array<Tenant>
      | Array<TenantHydrated>
      | Array<TenantHydratedTwice>
      | Array<TenantBase>;

    /**
     * Internal idempotency key used to prevent duplicate jobs.
     */
    dedupeKey: string;

    /**
     * Platform-local merge request or pull request number. Changing it alters job association.
     */
    codeReviewId: number;

    /**
     * Optional platform-local triggering comment number.
     */
    commentId?: number;

    /**
     * Provider-owned trigger identity encoded as JSON.
     */
    triggerJson: string;

    /**
     * Full commit SHA reviewed by this job. Changing it may make history inconsistent.
     */
    headSha: string;

    /**
     * System-managed job lifecycle state.
     */
    status:
      | "queued"
      | "in_progress"
      | "completed"
      | "failed"
      | "cancelled"
      | "expired";

    /**
     * Normalized event payload JSON. Invalid structure can prevent job processing.
     */
    payloadJson: string;

    /**
     * Retry attempts already made. Changing this affects retry behavior.
     */
    retryCount: number;
    lastError?: string;

    /**
     * ISO 8601 timestamp recorded when the job entered the queue.
     */
    enqueuedAt: string;

    /**
     * ISO 8601 timestamp when the job becomes eligible to claim. Retries push it forward.
     */
    availableAt: string;

    /**
     * ISO 8601 timestamp recorded when the job started processing.
     */
    startedAt?: string;

    /**
     * ISO 8601 timestamp recorded when the job finished processing.
     */
    finishedAt?: string;

    /**
     * Token of the current claim attempt. Ownership checks fence stale attempts by this value.
     */
    claimToken?: string;

    /**
     * Runner worker id that holds the current claim, for diagnostics.
     */
    claimedBy?: string;

    /**
     * ISO 8601 lease expiry for the current claim. A passed deadline allows reclaim.
     */
    claimExpiresAt?: string;

    /**
     * Logical id of the latest interaction run created for this job. Not a datasource relation.
     */
    latestInteractionRunId?: string;
  }

  export interface InteractionJob extends InteractionJobBase {
    tenantId: Array<DataLink>;
  }

  export interface InteractionJobHydrated extends InteractionJobBase {
    tenantId: Array<Tenant>;
  }

  export interface InteractionJobHydratedTwice extends InteractionJobBase {
    tenantId: Array<TenantHydrated>;
  }

  export namespace InteractionJob {
    export type FilterableFields = StringWithAutocomplete<
      | "tenantId"
      | "tenantId[*].type"
      | "tenantId[*].dataUrl"
      | "dedupeKey"
      | "codeReviewId"
      | "commentId"
      | "triggerJson"
      | "headSha"
      | "status"
      | "payloadJson"
      | "retryCount"
      | "lastError"
      | "enqueuedAt"
      | "availableAt"
      | "startedAt"
      | "finishedAt"
      | "claimToken"
      | "claimedBy"
      | "claimExpiresAt"
      | "latestInteractionRunId"
    >;
  }

  // #endregion

  // #region interaction_run

  export interface InteractionRunBase extends BaseObject<"interaction_run"> {
    interactionJobId:
      | Array<DataLink>
      | Array<InteractionJob>
      | Array<InteractionJobHydrated>
      | Array<InteractionJobHydratedTwice>
      | Array<InteractionJobBase>;
    tenantId:
      | Array<DataLink>
      | Array<Tenant>
      | Array<TenantHydrated>
      | Array<TenantHydratedTwice>
      | Array<TenantBase>;

    /**
     * Resolved model provider recorded for this run. Editing changes historical metadata.
     */
    provider: string;

    /**
     * Resolved review model recorded for this run. Editing changes historical metadata.
     */
    model?: string;
    modelProfileName?:
      | Array<DataLink>
      | Array<ModelProfile>
      | Array<ModelProfileHydrated>
      | Array<ModelProfileHydratedTwice>
      | Array<ModelProfileBase>;

    /**
     * Provider URL recorded for this run.
     */
    providerBaseUrl?: string;

    /**
     * Provider API type recorded for this run.
     */
    providerType?: string;

    /**
     * Resolved text generation model for this run.
     */
    textGenerationModel?: string;

    /**
     * Run lifecycle state. Manual changes may affect history queries and recovery.
     */
    status: "in_progress" | "completed" | "failed" | "cancelled";

    /**
     * Structured run result JSON. Invalid data can break history and review output.
     */
    resultJson?: string;
    error?: string;

    /**
     * ISO 8601 timestamp recorded when model execution started.
     */
    startedAt: string;
    finishedAt?: string;

    /**
     * Claim token that owned the job attempt that created this run. Used for lease recovery.
     */
    interactionJobClaimToken?: string;

    /**
     * Resolved review reasoning effort recorded for this run.
     */
    reviewReasoningEffort?: "low" | "medium" | "high" | "xhigh";

    /**
     * Resolved text generation reasoning effort recorded for this run.
     */
    textGenerationReasoningEffort?: "low" | "medium" | "high" | "xhigh";
  }

  export interface InteractionRun extends InteractionRunBase {
    interactionJobId: Array<DataLink>;
    tenantId: Array<DataLink>;
    modelProfileName?: Array<DataLink>;
  }

  export interface InteractionRunHydrated extends InteractionRunBase {
    interactionJobId: Array<InteractionJob>;
    tenantId: Array<Tenant>;
    modelProfileName?: Array<ModelProfile>;
  }

  export interface InteractionRunHydratedTwice extends InteractionRunBase {
    interactionJobId: Array<InteractionJobHydrated>;
    tenantId: Array<TenantHydrated>;
    modelProfileName?: Array<ModelProfileHydrated>;
  }

  export namespace InteractionRun {
    export type FilterableFields = StringWithAutocomplete<
      | "interactionJobId"
      | "interactionJobId[*].type"
      | "interactionJobId[*].dataUrl"
      | "tenantId"
      | "tenantId[*].type"
      | "tenantId[*].dataUrl"
      | "provider"
      | "model"
      | "modelProfileName"
      | "modelProfileName[*].type"
      | "modelProfileName[*].dataUrl"
      | "providerBaseUrl"
      | "providerType"
      | "textGenerationModel"
      | "status"
      | "resultJson"
      | "error"
      | "startedAt"
      | "finishedAt"
      | "interactionJobClaimToken"
      | "reviewReasoningEffort"
      | "textGenerationReasoningEffort"
    >;
  }

  // #endregion

  // #region interaction_run_metrics

  export interface InteractionRunMetricsBase extends BaseObject<"interaction_run_metrics"> {
    /**
     * Interaction run measured by this record.
     */
    interactionRunId:
      | Array<DataLink>
      | Array<InteractionRun>
      | Array<InteractionRunHydrated>
      | Array<InteractionRunHydratedTwice>
      | Array<InteractionRunBase>;

    /**
     * Harness implementation that produced this session.
     */
    harness: string;

    /**
     * Stable harness-native session identity.
     */
    harnessSessionKey: string;

    /**
     * Open session type reported by the harness.
     */
    sessionType: string;

    /**
     * Kind of event that initiated the measured run. Editing changes reporting metadata.
     */
    triggerKind?: string;

    /**
     * Prompt construction mode used for the run. Editing changes reporting metadata.
     */
    promptMode?: string;

    /**
     * Prompt size in characters.
     */
    promptChars: number;

    /**
     * Number of changed files included in prompt context.
     */
    promptContextChangedFiles: number;

    /**
     * Number of prior discussions included in prompt context.
     */
    promptContextPriorDiscussions: number;

    /**
     * Number of comments included in prompt context.
     */
    promptContextComments: number;

    /**
     * Number of assistant turns recorded for the run.
     */
    assistantTurns: number;

    /**
     * Number of assistant API calls recorded for the run.
     */
    assistantCalls: number;

    /**
     * Total tool executions recorded for the run.
     */
    toolExecutions: number;

    /**
     * Number of file-view tool calls recorded for the run.
     */
    viewToolCalls: number;

    /**
     * Number of file-glob tool calls recorded for the run.
     */
    globToolCalls: number;

    /**
     * Provider-reported input token count.
     */
    inputTokens: number;

    /**
     * Provider-reported output token count.
     */
    outputTokens: number;

    /**
     * Provider-reported cache read token count.
     */
    cacheReadTokens: number;

    /**
     * Provider-reported cache write token count.
     */
    cacheWriteTokens: number;

    /**
     * Provider-reported reasoning token count.
     */
    reasoningTokens: number;

    /**
     * Total provider API duration in milliseconds.
     */
    apiDurationMs: number;

    /**
     * Open namespaced unit key reported by the harness.
     */
    usageUnit?: string;

    /**
     * Amount expressed in usageUnit.
     */
    usageAmount?: number;

    /**
     * Per-model usage amounts encoded as JSON.
     */
    usageByModelJson: string;

    /**
     * Number of repeated file reads detected during the run.
     */
    repeatedViewReads: number;

    /**
     * Repeatedly viewed file paths encoded as JSON for diagnostics.
     */
    repeatedViewPathsJson: string;
  }

  export interface InteractionRunMetrics extends InteractionRunMetricsBase {
    interactionRunId: Array<DataLink>;
  }

  export interface InteractionRunMetricsHydrated extends InteractionRunMetricsBase {
    interactionRunId: Array<InteractionRun>;
  }

  export interface InteractionRunMetricsHydratedTwice extends InteractionRunMetricsBase {
    interactionRunId: Array<InteractionRunHydrated>;
  }

  export namespace InteractionRunMetrics {
    export type FilterableFields = StringWithAutocomplete<
      | "interactionRunId"
      | "interactionRunId[*].type"
      | "interactionRunId[*].dataUrl"
      | "harness"
      | "harnessSessionKey"
      | "sessionType"
      | "triggerKind"
      | "promptMode"
      | "promptChars"
      | "promptContextChangedFiles"
      | "promptContextPriorDiscussions"
      | "promptContextComments"
      | "assistantTurns"
      | "assistantCalls"
      | "toolExecutions"
      | "viewToolCalls"
      | "globToolCalls"
      | "inputTokens"
      | "outputTokens"
      | "cacheReadTokens"
      | "cacheWriteTokens"
      | "reasoningTokens"
      | "apiDurationMs"
      | "usageUnit"
      | "usageAmount"
      | "usageByModelJson"
      | "repeatedViewReads"
      | "repeatedViewPathsJson"
    >;
  }

  // #endregion

  // #region migrations

  export interface MigrationsBase extends BaseObject<"migrations"> {
    /**
     * Applied migration identifier managed by the storage adapter.
     */
    name: string;
  }

  export interface Migrations extends MigrationsBase {}

  export interface MigrationsHydrated extends MigrationsBase {}

  export interface MigrationsHydratedTwice extends MigrationsBase {}

  export namespace Migrations {
    export type FilterableFields = StringWithAutocomplete<"name">;
  }

  // #endregion

  // #region model_profile

  export interface ModelProfileBase extends BaseObject<"model_profile"> {
    /**
     * Stable profile name used by tenants.
     */
    name: string;

    /**
     * Absolute provider API URL. Leave empty for native Copilot access.
     */
    providerBaseUrl?: string;

    /**
     * API compatibility mode: openai, azure, or anthropic.
     */
    providerType?: "openai" | "azure" | "anthropic";

    /**
     * Provider credential or GitHub auth token that can access copilot.
     */
    authToken?: string;

    /**
     * Model used for reviews
     */
    reviewModel?: string;

    /**
     * Optional model for responding to comments or generating memory entries.
     */
    textGenerationModel?: string;

    /**
     * Optional reasoning effort for review sessions. Leave empty to use the harness default.
     */
    reviewReasoningEffort?: "low" | "medium" | "high" | "xhigh";

    /**
     * Optional reasoning effort for text-generation sessions. Leave empty to use the harness default.
     */
    textGenerationReasoningEffort?: "low" | "medium" | "high" | "xhigh";

    /**
     * OpenAI-compatible request format: completions or responses.
     */
    wireApi?: "completions" | "responses";

    /**
     * Used when a tenant has no explicit model profile.
     */
    isDefault: boolean;
  }

  export interface ModelProfile extends ModelProfileBase {}

  export interface ModelProfileHydrated extends ModelProfileBase {}

  export interface ModelProfileHydratedTwice extends ModelProfileBase {}

  export namespace ModelProfile {
    export type FilterableFields = StringWithAutocomplete<
      | "name"
      | "providerBaseUrl"
      | "providerType"
      | "authToken"
      | "reviewModel"
      | "textGenerationModel"
      | "reviewReasoningEffort"
      | "textGenerationReasoningEffort"
      | "wireApi"
      | "isDefault"
    >;
  }

  // #endregion

  // #region platform_connection

  export interface PlatformConnectionBase extends BaseObject<"platform_connection"> {
    /**
     * Immutable, globally unique connection name used in CLI.
     */
    name: string;

    /**
     * Provider slug, for example gitlab. Must match a loaded platform module.
     */
    platform: string;

    /**
     * Connection state. Set ready only when the provider configuration is complete.
     */
    status: "setup_required" | "ready";

    /**
     * Provider configuration JSON, including credentials. Invalid data can break the connection.
     */
    platformConnectionConfigJson: string;
  }

  export interface PlatformConnection extends PlatformConnectionBase {}

  export interface PlatformConnectionHydrated extends PlatformConnectionBase {}

  export interface PlatformConnectionHydratedTwice extends PlatformConnectionBase {}

  export namespace PlatformConnection {
    export type FilterableFields = StringWithAutocomplete<
      "name" | "platform" | "status" | "platformConnectionConfigJson"
    >;
  }

  // #endregion

  // #region project_memory

  export interface ProjectMemoryBase extends BaseObject<"project_memory"> {
    /**
     * Tenant that owns this project memory record.
     */
    tenantId:
      | Array<DataLink>
      | Array<Tenant>
      | Array<TenantHydrated>
      | Array<TenantHydratedTwice>
      | Array<TenantBase>;

    /**
     * Serialized project memory entries.
     */
    entriesJson: string;
  }

  export interface ProjectMemory extends ProjectMemoryBase {
    tenantId: Array<DataLink>;
  }

  export interface ProjectMemoryHydrated extends ProjectMemoryBase {
    tenantId: Array<Tenant>;
  }

  export interface ProjectMemoryHydratedTwice extends ProjectMemoryBase {
    tenantId: Array<TenantHydrated>;
  }

  export namespace ProjectMemory {
    export type FilterableFields = StringWithAutocomplete<
      "tenantId" | "tenantId[*].type" | "tenantId[*].dataUrl" | "entriesJson"
    >;
  }

  // #endregion

  // #region review_finding

  export interface ReviewFindingBase extends BaseObject<"review_finding"> {
    interactionRunId:
      | Array<DataLink>
      | Array<InteractionRun>
      | Array<InteractionRunHydrated>
      | Array<InteractionRunHydratedTwice>
      | Array<InteractionRunBase>;

    /**
     * Internal stable key used to match this finding across runs.
     */
    identityKey: string;

    /**
     * Finding impact: low, medium, high, or critical.
     */
    severity: "low" | "medium" | "high" | "critical";

    /**
     * Finding category used in review summaries and reconciliation.
     */
    category: string;

    /**
     * Finding title shown in review output. Editing does not update an existing platform comment.
     */
    title: string;

    /**
     * Finding details shown in review output. Editing does not update an existing platform comment.
     */
    body: string;

    /**
     * Source anchor JSON. Invalid values can prevent correct inline comment placement.
     */
    anchorJson?: string;

    /**
     * Optional suggestion JSON. Invalid values can prevent suggestion rendering.
     */
    suggestionJson?: string;

    /**
     * Finding state used by reconciliation. Manual changes affect future review summaries.
     */
    status: "open" | "resolved" | "dismissed";
  }

  export interface ReviewFinding extends ReviewFindingBase {
    interactionRunId: Array<DataLink>;
  }

  export interface ReviewFindingHydrated extends ReviewFindingBase {
    interactionRunId: Array<InteractionRun>;
  }

  export interface ReviewFindingHydratedTwice extends ReviewFindingBase {
    interactionRunId: Array<InteractionRunHydrated>;
  }

  export namespace ReviewFinding {
    export type FilterableFields = StringWithAutocomplete<
      | "interactionRunId"
      | "interactionRunId[*].type"
      | "interactionRunId[*].dataUrl"
      | "identityKey"
      | "severity"
      | "category"
      | "title"
      | "body"
      | "anchorJson"
      | "suggestionJson"
      | "status"
    >;
  }

  // #endregion

  // #region tenant

  export interface TenantBase extends BaseObject<"tenant"> {
    /**
     * Stable key generated by the platform adapter.
     */
    key: string;

    /**
     * Provider slug. It must match the selected platform connection.
     */
    platform: string;

    /**
     * Connection used by this tenant. Must match the tenant's platform.
     */
    platformConnectionId:
      | Array<DataLink>
      | Array<PlatformConnection>
      | Array<PlatformConnectionHydrated>
      | Array<PlatformConnectionHydratedTwice>
      | Array<PlatformConnectionBase>;

    /**
     * Provider-owned tenant JSON, including webhook secrets. Edit with caution.
     */
    platformConfigJson: string;

    /**
     * Optional model profile. Empty uses the default profile.
     */
    modelProfileName?:
      | Array<DataLink>
      | Array<ModelProfile>
      | Array<ModelProfileHydrated>
      | Array<ModelProfileHydratedTwice>
      | Array<ModelProfileBase>;
  }

  export interface Tenant extends TenantBase {
    platformConnectionId: Array<DataLink>;
    modelProfileName?: Array<DataLink>;
  }

  export interface TenantHydrated extends TenantBase {
    platformConnectionId: Array<PlatformConnection>;
    modelProfileName?: Array<ModelProfile>;
  }

  export interface TenantHydratedTwice extends TenantBase {
    platformConnectionId: Array<PlatformConnectionHydrated>;
    modelProfileName?: Array<ModelProfileHydrated>;
  }

  export namespace Tenant {
    export type FilterableFields = StringWithAutocomplete<
      | "key"
      | "platform"
      | "platformConnectionId"
      | "platformConnectionId[*].type"
      | "platformConnectionId[*].dataUrl"
      | "platformConfigJson"
      | "modelProfileName"
      | "modelProfileName[*].type"
      | "modelProfileName[*].dataUrl"
    >;
  }

  // #endregion

  export interface FlotiqObjectAPI {
    code_review_snapshot: ApiRequest<
      CodeReviewSnapshot,
      CodeReviewSnapshotHydrated,
      CodeReviewSnapshotHydratedTwice,
      CodeReviewSnapshot.FilterableFields
    >;

    discussion_mapping: ApiRequest<
      DiscussionMapping,
      DiscussionMappingHydrated,
      DiscussionMappingHydratedTwice,
      DiscussionMapping.FilterableFields
    >;

    interaction_job: ApiRequest<
      InteractionJob,
      InteractionJobHydrated,
      InteractionJobHydratedTwice,
      InteractionJob.FilterableFields
    >;

    interaction_run: ApiRequest<
      InteractionRun,
      InteractionRunHydrated,
      InteractionRunHydratedTwice,
      InteractionRun.FilterableFields
    >;

    interaction_run_metrics: ApiRequest<
      InteractionRunMetrics,
      InteractionRunMetricsHydrated,
      InteractionRunMetricsHydratedTwice,
      InteractionRunMetrics.FilterableFields
    >;

    migrations: ApiRequest<
      Migrations,
      MigrationsHydrated,
      MigrationsHydratedTwice,
      Migrations.FilterableFields
    >;

    model_profile: ApiRequest<
      ModelProfile,
      ModelProfileHydrated,
      ModelProfileHydratedTwice,
      ModelProfile.FilterableFields
    >;

    platform_connection: ApiRequest<
      PlatformConnection,
      PlatformConnectionHydrated,
      PlatformConnectionHydratedTwice,
      PlatformConnection.FilterableFields
    >;

    project_memory: ApiRequest<
      ProjectMemory,
      ProjectMemoryHydrated,
      ProjectMemoryHydratedTwice,
      ProjectMemory.FilterableFields
    >;

    review_finding: ApiRequest<
      ReviewFinding,
      ReviewFindingHydrated,
      ReviewFindingHydratedTwice,
      ReviewFinding.FilterableFields
    >;

    tenant: ApiRequest<
      Tenant,
      TenantHydrated,
      TenantHydratedTwice,
      Tenant.FilterableFields
    >;

    _generated_forms: ApiRequest<
      InternalGeneratedForms,
      InternalGeneratedFormsHydrated,
      InternalGeneratedFormsHydratedTwice,
      InternalGeneratedForms.FilterableFields
    >;

    _media: ApiRequest<
      InternalMedia,
      InternalMediaHydrated,
      InternalMediaHydratedTwice,
      InternalMedia.FilterableFields
    >;

    _plugin_settings: ApiRequest<
      InternalPluginSettings,
      InternalPluginSettingsHydrated,
      InternalPluginSettingsHydratedTwice,
      InternalPluginSettings.FilterableFields
    >;

    _tag: ApiRequest<
      InternalTag,
      InternalTagHydrated,
      InternalTagHydratedTwice,
      InternalTag.FilterableFields
    >;

    _webhooks: ApiRequest<
      InternalWebhooks,
      InternalWebhooksHydrated,
      InternalWebhooksHydratedTwice,
      InternalWebhooks.FilterableFields
    >;
  }

  export interface FlotiqSearchAPI {
    query<P extends SearchParams>(
      params?: P,
    ): Promise<
      HydratedSearchResponse<
        P,
        AnySpaceCTD,
        AnySpaceCTDHydrated,
        AnySpaceCTDHydratedTwice
      >
    >;
  }
}
