/**
 * This file was generated by flotiq-api-typegen command
 * Generated at: 2026-06-06T09:54:09.226Z
 */

import {
  DataLink,
  ApiRequest,
  BaseObject,
  SearchParams,
  HydratedSearchResponse,
  InternalGeneratedFormsBase,
  InternalGeneratedForms,
  InternalGeneratedFormsHydrated,
  InternalGeneratedFormsHydratedTwice,
  InternalMediaBase,
  InternalMedia,
  InternalMediaHydrated,
  InternalMediaHydratedTwice,
  InternalPluginSettingsBase,
  InternalPluginSettings,
  InternalPluginSettingsHydrated,
  InternalPluginSettingsHydratedTwice,
  InternalTagBase,
  InternalTag,
  InternalTagHydrated,
  InternalTagHydratedTwice,
  InternalWebhooksBase,
  InternalWebhooks,
  InternalWebhooksHydrated,
  InternalWebhooksHydratedTwice,
} from "@flotiq/flotiq-api-sdk";

type StringWithAutocomplete<T> = T | (string & Record<never, never>);

declare module "@flotiq/flotiq-api-sdk" {
  export type AnySpaceCTD =
    | CodeReviewSnapshot
    | DiscussionMapping
    | InteractionJob
    | InteractionRun
    | InteractionRunMetrics
    | Migrations
    | ModelProfile
    | PlatformConnection
    | ProjectMemory
    | ReviewFinding
    | Tenant
    | InternalGeneratedForms
    | InternalMedia
    | InternalPluginSettings
    | InternalTag
    | InternalWebhooks;

  export type AnySpaceCTDHydrated =
    | CodeReviewSnapshotHydrated
    | DiscussionMappingHydrated
    | InteractionJobHydrated
    | InteractionRunHydrated
    | InteractionRunMetricsHydrated
    | MigrationsHydrated
    | ModelProfileHydrated
    | PlatformConnectionHydrated
    | ProjectMemoryHydrated
    | ReviewFindingHydrated
    | TenantHydrated
    | InternalGeneratedFormsHydrated
    | InternalMediaHydrated
    | InternalPluginSettingsHydrated
    | InternalTagHydrated
    | InternalWebhooksHydrated;

  export type AnySpaceCTDHydratedTwice =
    | CodeReviewSnapshotHydratedTwice
    | DiscussionMappingHydratedTwice
    | InteractionJobHydratedTwice
    | InteractionRunHydratedTwice
    | InteractionRunMetricsHydratedTwice
    | MigrationsHydratedTwice
    | ModelProfileHydratedTwice
    | PlatformConnectionHydratedTwice
    | ProjectMemoryHydratedTwice
    | ReviewFindingHydratedTwice
    | TenantHydratedTwice
    | InternalGeneratedFormsHydratedTwice
    | InternalMediaHydratedTwice
    | InternalPluginSettingsHydratedTwice
    | InternalTagHydratedTwice
    | InternalWebhooksHydratedTwice;

  export type AnySpaceCTDBase =
    | CodeReviewSnapshotBase
    | DiscussionMappingBase
    | InteractionJobBase
    | InteractionRunBase
    | InteractionRunMetricsBase
    | MigrationsBase
    | ModelProfileBase
    | PlatformConnectionBase
    | ProjectMemoryBase
    | ReviewFindingBase
    | TenantBase
    | InternalGeneratedFormsBase
    | InternalMediaBase
    | InternalPluginSettingsBase
    | InternalTagBase
    | InternalWebhooksBase;

  // #region code_review_snapshot

  export interface CodeReviewSnapshotBase extends BaseObject<"code_review_snapshot"> {
    interactionJobId:
      | Array<DataLink>
      | Array<InteractionJob>
      | Array<InteractionJobHydrated>
      | Array<InteractionJobHydratedTwice>
      | Array<InteractionJobBase>;
    tenantId:
      | Array<DataLink>
      | Array<Tenant>
      | Array<TenantHydrated>
      | Array<TenantHydratedTwice>
      | Array<TenantBase>;
    codeReviewId: number;
    headSha: string;
    codeReviewJson: string;
    versionsJson: string;
    changesJson: string;
    commentsJson: string;
    discussionsJson: string;
    instructionsJson: string;
    projectMemoryJson?: string;
    workspaceStrategy: string;
  }

  export interface CodeReviewSnapshot extends CodeReviewSnapshotBase {
    interactionJobId: Array<DataLink>;
    tenantId: Array<DataLink>;
  }

  export interface CodeReviewSnapshotHydrated extends CodeReviewSnapshotBase {
    interactionJobId: Array<InteractionJob>;
    tenantId: Array<Tenant>;
  }

  export interface CodeReviewSnapshotHydratedTwice extends CodeReviewSnapshotBase {
    interactionJobId: Array<InteractionJobHydrated>;
    tenantId: Array<TenantHydrated>;
  }

  export namespace CodeReviewSnapshot {
    export type FilterableFields = StringWithAutocomplete<
      | "interactionJobId"
      | "interactionJobId[*].type"
      | "interactionJobId[*].dataUrl"
      | "tenantId"
      | "tenantId[*].type"
      | "tenantId[*].dataUrl"
      | "codeReviewId"
      | "headSha"
      | "codeReviewJson"
      | "versionsJson"
      | "changesJson"
      | "commentsJson"
      | "discussionsJson"
      | "instructionsJson"
      | "projectMemoryJson"
      | "workspaceStrategy"
    >;
  }

  // #endregion

  // #region discussion_mapping

  export interface DiscussionMappingBase extends BaseObject<"discussion_mapping"> {
    tenantId:
      | Array<DataLink>
      | Array<Tenant>
      | Array<TenantHydrated>
      | Array<TenantHydratedTwice>
      | Array<TenantBase>;
    codeReviewId: number;
    identityKey: string;
    findingFingerprint: string;
    title: string;
    severity: string;
    category: string;
    body: string;
    platformDiscussionId: string;
    platformCommentId: number;
    anchorJson?: string;
    positionJson?: string;
    botDiscussion: boolean;
    botComment: boolean;
    commentAuthorId?: number;
    commentAuthorUsername?: string;
    status: string;
    lastInteractionRunId?:
      | Array<DataLink>
      | Array<InteractionRun>
      | Array<InteractionRunHydrated>
      | Array<InteractionRunHydratedTwice>
      | Array<InteractionRunBase>;
  }

  export interface DiscussionMapping extends DiscussionMappingBase {
    tenantId: Array<DataLink>;
    lastInteractionRunId?: Array<DataLink>;
  }

  export interface DiscussionMappingHydrated extends DiscussionMappingBase {
    tenantId: Array<Tenant>;
    lastInteractionRunId?: Array<InteractionRun>;
  }

  export interface DiscussionMappingHydratedTwice extends DiscussionMappingBase {
    tenantId: Array<TenantHydrated>;
    lastInteractionRunId?: Array<InteractionRunHydrated>;
  }

  export namespace DiscussionMapping {
    export type FilterableFields = StringWithAutocomplete<
      | "tenantId"
      | "tenantId[*].type"
      | "tenantId[*].dataUrl"
      | "codeReviewId"
      | "identityKey"
      | "findingFingerprint"
      | "title"
      | "severity"
      | "category"
      | "body"
      | "platformDiscussionId"
      | "platformCommentId"
      | "anchorJson"
      | "positionJson"
      | "botDiscussion"
      | "botComment"
      | "commentAuthorId"
      | "commentAuthorUsername"
      | "status"
      | "lastInteractionRunId"
      | "lastInteractionRunId[*].type"
      | "lastInteractionRunId[*].dataUrl"
    >;
  }

  // #endregion

  // #region interaction_job

  export interface InteractionJobBase extends BaseObject<"interaction_job"> {
    tenantId:
      | Array<DataLink>
      | Array<Tenant>
      | Array<TenantHydrated>
      | Array<TenantHydratedTwice>
      | Array<TenantBase>;
    dedupeKey: string;
    codeReviewId: number;
    commentId?: number;
    triggerJson: string;
    headSha: string;
    status: string;
    payloadJson: string;
    retryCount: number;
    lastError?: string;
    enqueuedAt: string;
    startedAt?: string;
    finishedAt?: string;
  }

  export interface InteractionJob extends InteractionJobBase {
    tenantId: Array<DataLink>;
  }

  export interface InteractionJobHydrated extends InteractionJobBase {
    tenantId: Array<Tenant>;
  }

  export interface InteractionJobHydratedTwice extends InteractionJobBase {
    tenantId: Array<TenantHydrated>;
  }

  export namespace InteractionJob {
    export type FilterableFields = StringWithAutocomplete<
      | "tenantId"
      | "tenantId[*].type"
      | "tenantId[*].dataUrl"
      | "dedupeKey"
      | "codeReviewId"
      | "commentId"
      | "triggerJson"
      | "headSha"
      | "status"
      | "payloadJson"
      | "retryCount"
      | "lastError"
      | "enqueuedAt"
      | "startedAt"
      | "finishedAt"
    >;
  }

  // #endregion

  // #region interaction_run

  export interface InteractionRunBase extends BaseObject<"interaction_run"> {
    interactionJobId:
      | Array<DataLink>
      | Array<InteractionJob>
      | Array<InteractionJobHydrated>
      | Array<InteractionJobHydratedTwice>
      | Array<InteractionJobBase>;
    tenantId:
      | Array<DataLink>
      | Array<Tenant>
      | Array<TenantHydrated>
      | Array<TenantHydratedTwice>
      | Array<TenantBase>;
    provider: string;
    model?: string;
    modelProfileName?:
      | Array<DataLink>
      | Array<ModelProfile>
      | Array<ModelProfileHydrated>
      | Array<ModelProfileHydratedTwice>
      | Array<ModelProfileBase>;
    providerBaseUrl?: string;
    providerType?: string;
    textGenerationModel?: string;
    status: string;
    resultJson?: string;
    error?: string;
    startedAt: string;
    finishedAt?: string;
  }

  export interface InteractionRun extends InteractionRunBase {
    interactionJobId: Array<DataLink>;
    tenantId: Array<DataLink>;
    modelProfileName?: Array<DataLink>;
  }

  export interface InteractionRunHydrated extends InteractionRunBase {
    interactionJobId: Array<InteractionJob>;
    tenantId: Array<Tenant>;
    modelProfileName?: Array<ModelProfile>;
  }

  export interface InteractionRunHydratedTwice extends InteractionRunBase {
    interactionJobId: Array<InteractionJobHydrated>;
    tenantId: Array<TenantHydrated>;
    modelProfileName?: Array<ModelProfileHydrated>;
  }

  export namespace InteractionRun {
    export type FilterableFields = StringWithAutocomplete<
      | "interactionJobId"
      | "interactionJobId[*].type"
      | "interactionJobId[*].dataUrl"
      | "tenantId"
      | "tenantId[*].type"
      | "tenantId[*].dataUrl"
      | "provider"
      | "model"
      | "modelProfileName"
      | "modelProfileName[*].type"
      | "modelProfileName[*].dataUrl"
      | "providerBaseUrl"
      | "providerType"
      | "textGenerationModel"
      | "status"
      | "resultJson"
      | "error"
      | "startedAt"
      | "finishedAt"
    >;
  }

  // #endregion

  // #region interaction_run_metrics

  export interface InteractionRunMetricsBase extends BaseObject<"interaction_run_metrics"> {
    interactionRunId:
      | Array<DataLink>
      | Array<InteractionRun>
      | Array<InteractionRunHydrated>
      | Array<InteractionRunHydratedTwice>
      | Array<InteractionRunBase>;
    triggerKind?: string;
    promptMode?: string;
    promptChars: number;
    promptContextChangedFiles: number;
    promptContextPriorDiscussions: number;
    promptContextComments: number;
    assistantTurns: number;
    assistantCalls: number;
    toolExecutions: number;
    viewToolCalls: number;
    globToolCalls: number;
    inputTokens: number;
    outputTokens: number;
    cacheReadTokens: number;
    cacheWriteTokens: number;
    reasoningTokens: number;
    apiDurationMs: number;
    premiumRequests: number;
    repeatedViewReads: number;
    repeatedViewPathsJson: string;
  }

  export interface InteractionRunMetrics extends InteractionRunMetricsBase {
    interactionRunId: Array<DataLink>;
  }

  export interface InteractionRunMetricsHydrated extends InteractionRunMetricsBase {
    interactionRunId: Array<InteractionRun>;
  }

  export interface InteractionRunMetricsHydratedTwice extends InteractionRunMetricsBase {
    interactionRunId: Array<InteractionRunHydrated>;
  }

  export namespace InteractionRunMetrics {
    export type FilterableFields = StringWithAutocomplete<
      | "interactionRunId"
      | "interactionRunId[*].type"
      | "interactionRunId[*].dataUrl"
      | "triggerKind"
      | "promptMode"
      | "promptChars"
      | "promptContextChangedFiles"
      | "promptContextPriorDiscussions"
      | "promptContextComments"
      | "assistantTurns"
      | "assistantCalls"
      | "toolExecutions"
      | "viewToolCalls"
      | "globToolCalls"
      | "inputTokens"
      | "outputTokens"
      | "cacheReadTokens"
      | "cacheWriteTokens"
      | "reasoningTokens"
      | "apiDurationMs"
      | "premiumRequests"
      | "repeatedViewReads"
      | "repeatedViewPathsJson"
    >;
  }

  // #endregion

  // #region migrations

  export interface MigrationsBase extends BaseObject<"migrations"> {
    name: string;
  }

  export interface Migrations extends MigrationsBase {}

  export interface MigrationsHydrated extends MigrationsBase {}

  export interface MigrationsHydratedTwice extends MigrationsBase {}

  export namespace Migrations {
    export type FilterableFields = StringWithAutocomplete<"name">;
  }

  // #endregion

  // #region model_profile

  export interface ModelProfileBase extends BaseObject<"model_profile"> {
    name: string;
    providerBaseUrl?: string;
    providerType?: "openai" | "azure" | "anthropic";
    authToken?: string;
    reviewModel?: string;
    textGenerationModel?: string;
    wireApi?: "completions" | "responses";
    isDefault: boolean;
  }

  export interface ModelProfile extends ModelProfileBase {}

  export interface ModelProfileHydrated extends ModelProfileBase {}

  export interface ModelProfileHydratedTwice extends ModelProfileBase {}

  export namespace ModelProfile {
    export type FilterableFields = StringWithAutocomplete<
      | "name"
      | "providerBaseUrl"
      | "providerType"
      | "authToken"
      | "reviewModel"
      | "textGenerationModel"
      | "wireApi"
      | "isDefault"
    >;
  }

  // #endregion

  // #region platform_connection

  export interface PlatformConnectionBase extends BaseObject<"platform_connection"> {
    name: string;
    platform: string;
    status: "setup_required" | "ready";
    platformConnectionConfigJson: string;
  }

  export interface PlatformConnection extends PlatformConnectionBase {}

  export interface PlatformConnectionHydrated extends PlatformConnectionBase {}

  export interface PlatformConnectionHydratedTwice extends PlatformConnectionBase {}

  export namespace PlatformConnection {
    export type FilterableFields = StringWithAutocomplete<
      "name" | "platform" | "status" | "platformConnectionConfigJson"
    >;
  }

  // #endregion

  // #region project_memory

  export interface ProjectMemoryBase extends BaseObject<"project_memory"> {
    tenantId:
      | Array<DataLink>
      | Array<Tenant>
      | Array<TenantHydrated>
      | Array<TenantHydratedTwice>
      | Array<TenantBase>;
    entriesJson: string;
  }

  export interface ProjectMemory extends ProjectMemoryBase {
    tenantId: Array<DataLink>;
  }

  export interface ProjectMemoryHydrated extends ProjectMemoryBase {
    tenantId: Array<Tenant>;
  }

  export interface ProjectMemoryHydratedTwice extends ProjectMemoryBase {
    tenantId: Array<TenantHydrated>;
  }

  export namespace ProjectMemory {
    export type FilterableFields = StringWithAutocomplete<
      | "tenantId"
      | "tenantId[*].type"
      | "tenantId[*].dataUrl"
      | "entriesJson"
    >;
  }

  // #endregion

  // #region review_finding

  export interface ReviewFindingBase extends BaseObject<"review_finding"> {
    interactionRunId:
      | Array<DataLink>
      | Array<InteractionRun>
      | Array<InteractionRunHydrated>
      | Array<InteractionRunHydratedTwice>
      | Array<InteractionRunBase>;
    identityKey: string;
    severity: string;
    category: string;
    title: string;
    body: string;
    anchorJson?: string;
    suggestionJson?: string;
    status: string;
  }

  export interface ReviewFinding extends ReviewFindingBase {
    interactionRunId: Array<DataLink>;
  }

  export interface ReviewFindingHydrated extends ReviewFindingBase {
    interactionRunId: Array<InteractionRun>;
  }

  export interface ReviewFindingHydratedTwice extends ReviewFindingBase {
    interactionRunId: Array<InteractionRunHydrated>;
  }

  export namespace ReviewFinding {
    export type FilterableFields = StringWithAutocomplete<
      | "interactionRunId"
      | "interactionRunId[*].type"
      | "interactionRunId[*].dataUrl"
      | "identityKey"
      | "severity"
      | "category"
      | "title"
      | "body"
      | "anchorJson"
      | "suggestionJson"
      | "status"
    >;
  }

  // #endregion

  // #region tenant

  export interface TenantBase extends BaseObject<"tenant"> {
    /**
     * Unique key generated by the platform adapter.
     */
    key: string;
    platform: string;
    platformConnectionId:
      | Array<DataLink>
      | Array<PlatformConnection>
      | Array<PlatformConnectionHydrated>
      | Array<PlatformConnectionHydratedTwice>
      | Array<PlatformConnectionBase>;
    platformConfigJson: string;
    modelProfileName?:
      | Array<DataLink>
      | Array<ModelProfile>
      | Array<ModelProfileHydrated>
      | Array<ModelProfileHydratedTwice>
      | Array<ModelProfileBase>;
  }

  export interface Tenant extends TenantBase {
    platformConnectionId: Array<DataLink>;
    modelProfileName?: Array<DataLink>;
  }

  export interface TenantHydrated extends TenantBase {
    platformConnectionId: Array<PlatformConnection>;
    modelProfileName?: Array<ModelProfile>;
  }

  export interface TenantHydratedTwice extends TenantBase {
    platformConnectionId: Array<PlatformConnectionHydrated>;
    modelProfileName?: Array<ModelProfileHydrated>;
  }

  export namespace Tenant {
    export type FilterableFields = StringWithAutocomplete<
      | "key"
      | "platform"
      | "platformConnectionId"
      | "platformConnectionId[*].type"
      | "platformConnectionId[*].dataUrl"
      | "platformConfigJson"
      | "modelProfileName"
      | "modelProfileName[*].type"
      | "modelProfileName[*].dataUrl"
    >;
  }

  // #endregion

  export interface FlotiqObjectAPI {
    code_review_snapshot: ApiRequest<
      CodeReviewSnapshot,
      CodeReviewSnapshotHydrated,
      CodeReviewSnapshotHydratedTwice,
      CodeReviewSnapshot.FilterableFields
    >;

    discussion_mapping: ApiRequest<
      DiscussionMapping,
      DiscussionMappingHydrated,
      DiscussionMappingHydratedTwice,
      DiscussionMapping.FilterableFields
    >;

    interaction_job: ApiRequest<
      InteractionJob,
      InteractionJobHydrated,
      InteractionJobHydratedTwice,
      InteractionJob.FilterableFields
    >;

    interaction_run: ApiRequest<
      InteractionRun,
      InteractionRunHydrated,
      InteractionRunHydratedTwice,
      InteractionRun.FilterableFields
    >;

    interaction_run_metrics: ApiRequest<
      InteractionRunMetrics,
      InteractionRunMetricsHydrated,
      InteractionRunMetricsHydratedTwice,
      InteractionRunMetrics.FilterableFields
    >;

    migrations: ApiRequest<
      Migrations,
      MigrationsHydrated,
      MigrationsHydratedTwice,
      Migrations.FilterableFields
    >;

    model_profile: ApiRequest<
      ModelProfile,
      ModelProfileHydrated,
      ModelProfileHydratedTwice,
      ModelProfile.FilterableFields
    >;

    platform_connection: ApiRequest<
      PlatformConnection,
      PlatformConnectionHydrated,
      PlatformConnectionHydratedTwice,
      PlatformConnection.FilterableFields
    >;

    project_memory: ApiRequest<
      ProjectMemory,
      ProjectMemoryHydrated,
      ProjectMemoryHydratedTwice,
      ProjectMemory.FilterableFields
    >;

    review_finding: ApiRequest<
      ReviewFinding,
      ReviewFindingHydrated,
      ReviewFindingHydratedTwice,
      ReviewFinding.FilterableFields
    >;

    tenant: ApiRequest<
      Tenant,
      TenantHydrated,
      TenantHydratedTwice,
      Tenant.FilterableFields
    >;

    _generated_forms: ApiRequest<
      InternalGeneratedForms,
      InternalGeneratedFormsHydrated,
      InternalGeneratedFormsHydratedTwice,
      InternalGeneratedForms.FilterableFields
    >;

    _media: ApiRequest<
      InternalMedia,
      InternalMediaHydrated,
      InternalMediaHydratedTwice,
      InternalMedia.FilterableFields
    >;

    _plugin_settings: ApiRequest<
      InternalPluginSettings,
      InternalPluginSettingsHydrated,
      InternalPluginSettingsHydratedTwice,
      InternalPluginSettings.FilterableFields
    >;

    _tag: ApiRequest<
      InternalTag,
      InternalTagHydrated,
      InternalTagHydratedTwice,
      InternalTag.FilterableFields
    >;

    _webhooks: ApiRequest<
      InternalWebhooks,
      InternalWebhooksHydrated,
      InternalWebhooksHydratedTwice,
      InternalWebhooks.FilterableFields
    >;
  }

  export interface FlotiqSearchAPI {
    query<P extends SearchParams>(
      params?: P,
    ): Promise<
      HydratedSearchResponse<
        P,
        AnySpaceCTD,
        AnySpaceCTDHydrated,
        AnySpaceCTDHydratedTwice
      >
    >;
  }
}
